### ISSUE TITLE
verify function?

### ISSUE THREAD

**Issue by omar2205** [denosaurs/argontwo#1]
Is there any verification function?

**Comment by eliassjogreen** [comment]
No, to verify a hash you would simply hash it and compare the hashed bytes and the stored hash. If that is not what you meant, please elaborate.

**Comment by omar2205** [comment]
That's what I did. Thanks.

**Comment by J053Fabi0** [comment]
I would use [timingSafeEqual](https://jsr.io/@std/crypto@0.224.0/doc/timing-safe-equal/~/timingSafeEqual):

```ts
import { timingSafeEqual } from "@std/crypto/timing-safe-equal";

export function compare(token: string, hashed: ArrayBuffer): boolean {
  return timingSafeEqual(hash(token), hashed);
}
```
