### ISSUE TITLE
Storing hash in DB

### ISSUE THREAD

**Issue by sudo-sand** [denosaurs/argontwo#2]
In node, I used argon2 to generate this password hash

```$argon2id$v=19$m=4096,t=3,p=1$bP3C3FogLCQkvFX/EgwTlQ$q/BKd05LNG9NK3qE4mWV03Jpr/5hQNtZF/8V/vkkUXg```

But in argontwo it generates a Uint8Array. How to get the above value?

**Comment by eliassjogreen** [comment]
What you are looking for are [PHC](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) strings, my recommendation is to use: [@phc/format](https://github.com/simonepri/phc-format) imported from `esm.sh/@phc/format` and implement a thin wrapper over the hash function to automatically encode all parameters and get such a string.

**Comment by sudo-sand** [comment]
@eliassjogreen Can you please provide an example comparing two password?

**Comment by eliassjogreen** [comment]
To do a simple and safe comparison you should do the following:

```ts
import { timingSafeEqual } from "https://deno.land/std@0.155.0/crypto/timing_safe_equal.ts";
import { hash } from "https://deno.land/x/argontwo@0.1.1/mod.ts";

const encoder = new TextEncoder();

// Store the salt and hash, this could be done with a PHC string or just as is.
// Using a PHC string you would use the `phc.serialize` function to encode it
const salt1 = new Uint8Array(40);
crypto.getRandomValues(salt1);
const hash1 = hash(encoder.encode("example password 1"), salt1);

// Serializing as PHC, this is when you would want to store it in the database
const phc1 = phc.serialize({
  id: "argon2id",
  version: 19,
  params: {
    m: 4096,
    t: 3,
    p: 1
  },
  salt: salt1,
  hash: hash1,
});

// Deserializing the PHC string, probably directly fetched from a database in a real-life scenario
const { salt: salt2, hash: hash2 } = phc.deserialize(phc1);

// Using timing safe equal protects against timing based attacks
console.log(timingSafeEqual(hash1, hash2));

// You would probably not compare the `hash1` variable with `hash2` as they should be identical
// Instead you would hash the plaintext password which has been sent in with the deserialized salt
// and compare it with the deserialized hash which you have fetched from the database and earlier
// stored as an PHC string.
```

**Comment by sudo-sand** [comment]
Thanks @eliassjogreen

**Comment by smnbonino** [comment]
@eliassjogreen I am trying to use the example you provided, but I am getting this error:

**salt must be a Buffer**

> 26 |       const phc1 = phc.serialize({
     |                        ^
  27 |         id: "argon2id",
  28 |         version: 19,
  29 |         params: {

TypeError: salt must be a Buffer
    at Object.N [as serialize] (https://esm.sh/v132/@phc/format@1.0.0/denonext/format.mjs:3:2235)

Deno does not support the "node" Buffer and the only workaround I have found is to use Buffer from https://deno.land/std@0.136.0/node/buffer.ts. Are there better solutions?

**Comment by eliassjogreen** [comment]
@binarypillow The current PHC package seems far from ideal. I might just create my own module for it as it seems quite requested, both here and in the deno discord. It also seems it isn't really maintained, and I couldn't find any good alternatives.

In the meanwhile suggest doing the workaround; I also created an example in [./examples/phc.ts](https://github.com/denosaurs/argontwo/blob/main/examples/phc.ts) (#6) which uses the `node:buffer` as you suggest to allow `@phc/format` to function properly.

**Comment by smnbonino** [comment]
> @binarypillow The current PHC package seems far from ideal. I might just create my own module for it as it seems quite requested, both here and in the deno discord.

It would be greatly appreciated if you did.

**Comment by smnbonino** [comment]
I also found this module https://deno.land/x/scrypt@v4.2.1 which uses a customised version of PHC, if you want to check it out.
