### ISSUE TITLE
Update default parameters with OWASP recommondations

### ISSUE THREAD

**Issue by arnoldderoij** [denosaurs/argontwo#3]
While investigating to use this library in my project, I noticed the default parameters of this Argon2id implementation are outdated.
https://github.com/denosaurs/argontwo/blob/1e374079dd90a6b86a3fe219906cd4055d150189/mod.ts#L72-L83

To make sure the user of the default library parameters is using secure Argon2id parameters, I would suggest to update the default parameters to one of the following configurations recommended by OWASP:
-  m=47104 (46 MiB), t=1, p=1 (Do not use with Argon2i)
-  m=19456 (19 MiB), t=2, p=1 (Do not use with Argon2i)
-  m=12288 (12 MiB), t=3, p=1
-  m=9216 (9 MiB), t=4, p=1
-  m=7168 (7 MiB), t=5, p=1

(2023-10-18 source: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id)

**Comment by eliassjogreen** [comment]
Thank you for noticing! I am working on PR which refactors and updates the module. The rust dependencies also needed an update, we used `wee_alloc` before which is no longer maintained and had a potential memory leak.

**Comment by arnoldderoij** [comment]
Wow @eliassjogreen, you're fast! thanks ❤️
